'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18449
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WindowsApplication3.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _31_5_2013_17_31_09_6gfeuhi1gbomn16mfl3kiusa63_liq99i2i() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("31_5_2013_17_31_09_6gfeuhi1gbomn16mfl3kiusa63_liq99i2i", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _84087() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("84087", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8589130568906_red_and_grey_wallpaper_hd() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8589130568906-red-and-grey-wallpaper-hd", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _8589130568906_red_and_grey_wallpaper_hd1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("8589130568906-red-and-grey-wallpaper-hd1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Best_top_desktop_abstract_pattern_wallpapers_hd_wallpaper_pattern_pictures_and_images_47() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Best-top-desktop-abstract-pattern-wallpapers-hd-wallpaper-pattern-pictures-and-im"& _ 
                        "ages-47", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property brown_background_1_free_background_and_wallpaper__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("brown-background-1-free-background-and-wallpaper (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cmdk() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cmdk", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property COURSES() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("COURSES", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property cp_5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("cp_5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property final() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("final", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property front_page() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("front page", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property header() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("header", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property header_2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("header_2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property HOSTEL__() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("HOSTEL -", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property light_grey_and_white_wrinkled_texture_medium() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("light-grey-and-white-wrinkled-texture_medium", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property myhc_4882() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("myhc_4882", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PLACEMENTS() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PLACEMENTS", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Red_and_Grey_Wallpaper_by_se8015() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Red_and_Grey_Wallpaper_by_se8015", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property soSor6PH9kBw42jzFEI5dbbN9rWdALmcPYATEJnyZhiJguXZ1OBzgrsRNEp9jvGx() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("soSor6PH9kBw42jzFEI5dbbN9rWdALmcPYATEJnyZhiJguXZ1OBzgrsRNEp9jvGx", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property SPORTS__() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SPORTS -", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property voaphotos022865() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("voaphotos022865", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property voaphotos0228651() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("voaphotos0228651", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
